/* ==========================================================
   TECHNO JAPAN — SHARED DATA

   Edit this file to update artists, events, and venues across all pages.
   events.html, artists.html, venues.html, discover.html, and map.html
   all read from here.
   ========================================================== */

const ARTISTS = [
  {
    id: "dj-nobu",
    name: "DJ Nobu",
    city: "CHIBA",
    country: "JAPAN",
    genre: "TECHNO",
    image: "images/artists/dj-nobu.jpg",
    bio: "DJ Nobu is a Chiba-based techno artist deeply embedded in Japan's underground electronic music scene. Known for his precise technical approach and atmospheric sound design, he represents the evolution of Japanese techno with a distinctly minimalist aesthetic.",
    links: {
      instagram: "https://www.instagram.com/dj_nobu_ft/",
      soundcloud: "https://soundcloud.com/djnobu_bitta",
      bandcamp: "https://dj-nobu.bandcamp.com/album/sh",
    }
  },
  {
    id: "wata-igarashi",
    name: "WATA IGARASHI",
    city: "TOKYO",
    country: "JAPAN",
    genre: "TECHNO",
    image: "images/artists/wata-igarashi.jpg",
    bio: "Tokyo-based producer and DJ crafting hypnotic, psychedelic techno. Releases on Midgar, The Bunker NY, and his own Meditate label. His sound is a deep, spiraling journey — transcendent and relentless.",
    links: {
      instagram: "https://www.instagram.com/wataigarashi/",
      soundcloud: "https://soundcloud.com/wataigarashi",
      bandcamp: "https://wataigarashi.bandcamp.com/",
    }
  },
  {
    id: "kotsu",
    name: "KOTSU",
    city: "OSAKA",
    country: "JAPAN",
    genre: "HOUSE / MINIMAL",
    image: "images/artists/kotsu.jpg",
    bio: "Osaka selector with deep roots in the Kansai underground. Fluid sets moving between deep house, minimal, and micro-house. A fixture at CIRCUS Osaka and a regular across Japan's club circuit.",
    links: {
      instagram: "https://www.instagram.com/kotsu_dj/",
      soundcloud: "https://soundcloud.com/kotsu",
    }
  },
  {
    id: "ken-ishii",
    name: "KEN ISHII",
    city: "TOKYO",
    country: "JAPAN",
    genre: "TECHNO",
    image: "images/artists/ken-ishii.jpg",
    bio: "Pioneer of Japanese techno since the early '90s. Internationally recognized through releases on R&S Records and Sublime. A living legend whose influence on Japan's electronic music scene is immeasurable.",
    links: {
      instagram: "https://www.instagram.com/kenishiiofficial/",
      soundcloud: "https://soundcloud.com/ken-ishii-70drums",
      bandcamp: "https://kenishii.bandcamp.com/",
      website: "https://kenishii.com",
    }
  },
  {
    id: "dj-miku",
    name: "Dj Miku",
  },
  {
    id: "dj-kensei",
    name: "Dj Kensei",
  },
  {
    id: "dj-yogurt",
    name: "Dj Yogurt",
  },
  {
    id: "hidai",
    name: "Hidai",
  },
  {
    id: "taichi-kawahira",
    name: "Taichi Kawahira",
  },
  {
    id: "tsutomu",
    name: "Tsutomu",
  },
  {
    id: "qmico",
    name: "Qmico",
  },
  {
    id: "ga-su",
    name: "Ga Su",
  },
  {
    id: "freecinn",
    name: "Freecinn",
  },
  {
    id: "nutmeg",
    name: "Nutmeg",
  },
  {
    id: "snipe1",
    name: "Snipe1",
  },
  {
    id: "liarako",
    name: "Liarako",
  },
  {
    id: "akey",
    name: "Akey",
  },
  {
    id: "ayumu",
    name: "Ayumu",
  },
  {
    id: "captain-k",
    name: "Captain K",
  },
  {
    id: "lowki",
    name: "Lowki",
  },
  {
    id: "masa-aka-kyounote",
    name: "Masa Aka Kyounote",
  },
  {
    id: "menou--iwamaki",
    name: "Menou  Iwamaki",
  },
  {
    id: "mimu",
    name: "Mimu",
  },
  {
    id: "naotsun",
    name: "Naotsun",
  },
  {
    id: "norid",
    name: "Norid",
  },
  {
    id: "sakuma",
    name: "Sakuma",
  },
  {
    id: "seco",
    name: "Seco",
  },
  {
    id: "shimoyan",
    name: "Shimoyan",
  },
  {
    id: "tada",
    name: "Tada",
  },
  {
    id: "yazzus",
    name: "Yazzus",
  },
  {
    id: "cosmic-caz",
    name: "Cosmic Caz",
  },
  {
    id: "janus-rose",
    name: "Janus Rose",
  },
  {
    id: "mayudepth",
    name: "Mayudepth",
  },
  {
    id: "akii",
    name: "Akii",
  },
  {
    id: "mio",
    name: "Mio",
  },
  {
    id: "aliceyuki",
    name: "Aliceyuki",
  },
  {
    id: "akaaki-ito",
    name: "Akaaki Ito",
  },
  {
    id: "choko",
    name: "Choko",
  },
  {
    id: "akihiro-suzuki",
    name: "Akihiro Suzuki",
  },
  {
    id: "endorphin",
    name: "Endorphin",
  },
  {
    id: "kevin-miyagi",
    name: "Kevin Miyagi",
  },
  {
    id: "psychogem",
    name: "Psychogem",
  },
  {
    id: "sho",
    name: "Sho",
  },
  {
    id: "takehiro-imaizumi",
    name: "Takehiro Imaizumi",
  },
  {
    id: "tazzy",
    name: "Tazzy",
  },
  {
    id: "tko",
    name: "Tko",
  },
  {
    id: "tmak",
    name: "Tmak",
  },
  {
    id: "yeark",
    name: "Yeark",
  },
  {
    id: "yuripon",
    name: "Yuripon",
  },
  {
    id: "198",
    name: "198",
  },
  {
    id: "antal--hunee",
    name: "Antal  Hunee",
  },
  {
    id: "ben-ufo",
    name: "Ben Ufo",
  },
  {
    id: "daphni",
    name: "Daphni",
  },
  {
    id: "dj-maria",
    name: "Dj Maria",
  },
  {
    id: "dungeoneering-albino-sound--daigos",
    name: "Dungeoneering Albino Sound  Daigos",
  },
  {
    id: "feline",
    name: "Feline",
  },
  {
    id: "floating-points",
    name: "Floating Points",
  },
  {
    id: "gerd-janson",
    name: "Gerd Janson",
  },
  {
    id: "gonno",
    name: "Gonno",
  },
  {
    id: "haai",
    name: "Haai",
  },
  {
    id: "helena-hauff",
    name: "Helena Hauff",
  },
  {
    id: "jonathan-kusuma",
    name: "Jonathan Kusuma",
  },
  {
    id: "jonny-rock",
    name: "Jonny Rock",
  },
  {
    id: "kikiorix",
    name: "Kikiorix",
  },
  {
    id: "mala",
    name: "Mala",
  },
  {
    id: "nc4k-stones-taro--lomax",
    name: "Nc4k Stones Taro  Lomax",
  },
  {
    id: "sisi-b2b-ouissam-b2b-yamarchy",
    name: "Sisi B2b Ouissam B2b Yamarchy",
  },
  {
    id: "suze-ij",
    name: "Suze Ij",
  },
  {
    id: "four-tet",
    name: "Four Tet",
  },
];

const EVENTS = [
  {
    name: "UNDERGROUND FREQUENCY",
    date: "2026-05-16T15:00:00.000Z",
    venue: "CONTACT",
    city: "TOKYO",
    time: "23:00 - 05:00",
    desc: "A night of raw, unfiltered techno featuring local and international selectors.",
    lineup: ["dj-nobu", "wata-igarashi"],
  },
  {
    name: "DAWN PATROL",
    date: "2026-05-30T15:00:00.000Z",
    venue: "CIRCUS",
    city: "OSAKA",
    time: "22:00 - 06:00",
    desc: "Deep house and minimal techno. Sunrise session on the terrace.",
    lineup: ["kotsu", "mayurashka"],
  },
  {
    name: "RURAL FESTIVAL 2026",
    date: "2026-07-18T15:00:00.000Z",
    venue: "NAEBA SKI RESORT",
    city: "NIIGATA",
    time: "ALL DAY",
    desc: "Three-day open-air festival in the mountains. Techno, house, ambient, and beyond.",
    lineup: ["ken-ishii", "dj-nobu", "wata-igarashi", "kotsu"],
  },
  {
    name: "CONCRETE ECHOES",
    date: "2026-06-13T15:00:00.000Z",
    venue: "WAREHOUSE 702",
    city: "TOKYO",
    time: "22:00 - 05:00",
    desc: "Industrial space, concrete walls, heavy sound. Warehouse techno at its finest.",
    lineup: ["wata-igarashi"],
  },
  {
    name: "CAPSULE",
    date: "2026-04-04T15:00:00.000Z",
    venue: "CONTACT",
    city: "TOKYO",
    time: "23:00 - 05:00",
    desc: "Intimate club night focused on minimal and micro-house.",
    lineup: ["mayurashka", "cabanne"],
  },
  {
    name: "ZERO GRAVITY",
    date: "2026-03-21T15:00:00.000Z",
    venue: "CLUB METRO",
    city: "KYOTO",
    time: "22:00 - 04:00",
    desc: "Kyoto's longest-running underground techno night.",
    lineup: ["cabanne"],
  },
  {
    name: "AFTER HOURS COLLECTIVE",
    date: "2026-08-08T15:00:00.000Z",
    venue: "VENT",
    city: "TOKYO",
    time: "28:00 - 10:00",
    desc: "After-hours session. Hypnotic, deep, relentless.",
    lineup: ["dj-nobu", "ken-ishii"],
  },
];

const FESTIVALS = [
  {
    id: "snow-machine-japan",
    type: "festival",
    name: "Snow Machine Japan",
    date: "2026-03-03/2026-03-08",
    location: "HAKUBA VALLEY",
    city: "Hakuba",
    address: "Kitajo, Hakuba Village, Kitaazumi District, Nagano Prefecture",
    lat: 36.6982,
    lng: 137.8619,
    image: "images/festivals/snow-machine-japan.jpeg",
    flyer: "images/festivals/snow-machine-japan-flyer.jpg",
    genre: ["TECHNO", "HOUSE", "LIVE", "OTHERS"],
    desc: "Snow Machine Japan transforms the alpine resort town of Hakuba into a winter playground for electronic music enthusiasts. The festival combines skiing and snowboarding culture with carefully curated lineups spanning techno and house music. Set against the backdrop of the Japanese Alps, it offers an intimate alternative to the larger summer festival circuit.",
    url: "https://hakuba.snow-machine.com/ja/",
    instagram: "https://www.instagram.com/snowmachinejapan/",
  },
  {
    id: "doofing-park",
    type: "rave",
    name: "DOOFING PARK",
    date: "2026-04-04/2026-04-05",
    location: "Secret Location",
    city: "KANTO",
    genre: ["TECHNO"],
    desc: "DOOFING PARK brings outdoor techno culture to Tokyo's concrete landscape, focusing on raw sound systems and community-driven programming. The event emphasizes the underground ethos of free party culture within Japan's highly regulated festival environment.",
    instagram: "https://www.instagram.com/captain_k.doofingpark/",
    lineup: ["Akey", "AYUMU", "CAPTAIN-K", "HIDAI", "Lowki", "masa a.k.a kyounote", "Menou / iwamaki", "Mimu", "naotsun", "NORID", "Sakuma", "SECO", "Shimoyan", "TADA"],
  },
  {
    id: "waifu",
    type: "rave",
    name: "WAIFU",
    date: "2026-04-10T15:00:00.000Z",
    location: "Kinone Pension",
    city: "Chiba",
    address: "296-1 Kinone, Narita City, Chiba Prefecture",
    lat: 35.7609,
    lng: 140.3924,
    image: "images/festivals/waifu.jpeg",
    genre: ["TECHNO"],
    desc: "WAIFU brings together anime culture and electronic music in Chiba's underground scene. The party blends otaku aesthetics with serious dancefloor programming, creating a unique space where Japanese pop culture meets contemporary club music.",
    url: "https://waifu-party.tokyo/",
    instagram: "https://www.instagram.com/waifu_party/",
    lineup: ["Yazzus", "Cosmic Caz", "Janus Rose", "MAYUDEPTH", "akii", "M.I.O", "Aliceyuki"],
  },
  {
    id: "arch",
    type: "rave",
    name: "ARCH 2025",
    date: "2026-04-11/2026-04-12",
    location: "Odaira no Sato Camp Area",
    city: "Gunma",
    address: "495 Kodaira, Omama-cho, Midori City, Gunma Prefecture",
    lat: 36.4303,
    lng: 139.2767,
    image: "images/festivals/arch-2025.jpeg",
    flyer: "images/festivals/arch-flyer.jpg",
    genre: ["TECHNO", "HOUSE"],
    desc: "ARCH returns to Gunma for its eleventh edition, maintaining its reputation as one of Japan's most respected underground gatherings. The festival continues to showcase cutting-edge techno programming in an intimate setting that prioritizes sound quality and artistic integrity over commercial appeal.",
    instagram: "https://www.instagram.com/arch___2014/",
    lineup: ["CHOKO", "CAPTAIN-K", "AKIHIRO SUZUKI", "ENDORPHIN", "KEVIN MIYAGI", "PSYCHOGEM", "SHO", "TAKEHIRO IMAIZUMI", "TAZZY", "TKO", "TMAK", "YEARK", "YURIPON", "青", "198"],
  },
  {
    id: "rainbow-disco-club",
    type: "festival",
    name: "Rainbow Disco Club",
    date: "2026-04-17/2026-04-19",
    location: "Higashi-Izu Cross Country Course",
    city: "Shizuoka",
    address: "Inatori, Higashiizu-cho, Kamo-gun, Shizuoka Prefecture",
    lat: 34.7847,
    lng: 139.0262,
    image: "images/festivals/rainbow-disco-club.jpeg",
    flyer: "images/festivals/rainbow-disco-club-flyer.jpg",
    genre: ["TECHNO", "HOUSE"],
    desc: "Rainbow Disco Club takes place at the Higashi-Izu Cross Country Course in Shizuoka, transforming the natural terrain into an outdoor dance floor. The festival combines house and techno programming with Japan's scenic countryside setting. Known for its intimate scale and carefully curated lineup that balances international and domestic acts.",
    url: "https://www.rainbowdiscoclub.com/",
    instagram: "https://www.instagram.com/rainbowdiscoclub/",
    lineup: ["Antal & Hunee", "Ben UFO", "Daphni", "DJ Maria.", "Dungeoneering (Albino Sound & Daigos)", "Feline", "Floating Points", "Gerd Janson", "Gonno", "HAAi", "Helena Hauff", "Jonathan Kusuma", "Jonny Rock", "Kikiorix", "Mala", "NC4K (Stones Taro & Lomax)", "Sisi b2b Ouissam b2b Yamarchy", "Suze Ijó", "Four Tet"],
  },
  {
    id: "ala",
    type: "rave",
    name: "ALA",
    date: "2026-04-18/2026-04-19",
    location: "Toriki Tsuribori Cafe & Campground",
    city: "Chiba",
    address: "1508 Ogami, Mutsuzawa-machi, Chosei-gun, Chiba Prefecture",
    lat: 35.3265,
    lng: 140.2882,
    image: "images/festivals/ala.jpg",
    flyer: "images/festivals/ala-flyer.jpg",
    genre: ["TECHNO", "AMBIENT"],
    desc: "ALA brings together Japan's underground electronic music community in Chiba with a focus on psychedelic and trippy soundscapes. The festival showcases both local and international artists across multiple stages, emphasizing immersive audiovisual experiences that blur the lines between genres.",
    url: "https://www.ala-jp.net/",
    instagram: "https://www.instagram.com/ala_trippymusic/",
    lineup: ["DJ MIKU", "DJ KENSEI", "DJ Yogurt", "HIDAI", "TAICHI KAWAHIRA", "TSUTOMU", "Qmico", "GA-SU", "free☆cinn.", "NUTMEG", "snipe1", "LiaRako"],
  },
  {
    id: "osukinidouzo",
    name: "おすきにどうぞ2025",
    date: "2026-05-02/2026-05-04",
    city: "Kanagawa",
    genre: ["EXPERIMENTAL", "ELECTRONIC"],
    desc: "A carefully curated gathering in Kanagawa that emphasizes artistic freedom and community over commercial spectacle. The festival maintains an intimate scale while showcasing both established and emerging artists across electronic music's more experimental territories.",
  },
  {
    id: "transcendence",
    type: "rave",
    name: "Transcendence",
    date: "2026-05-08/2026-05-10",
    location: "Choujya no Mori",
    city: "Nagano",
    address: "5616-6 Kitaaiki Village, Minamisaku District, Nagano Prefecture",
    lat: 36.0592,
    lng: 138.5512,
    image: "images/festivals/transcendence.jpeg",
    flyer: "images/festivals/transcendence-flyer.jpg",
    genre: ["TECHNO"],
    desc: "Transcendence delivers uncompromising techno programming in the mountainous terrain surrounding Nagano. The festival leverages Japan's natural acoustics and topography to create an immersive experience that bridges underground electronic music culture with the country's distinctive festival ecosystem. Its focus remains firmly on the music, drawing both domestic and international artists to perform in this unique alpine setting.",
    url: "https://transcendence-jp.com/",
    instagram: "https://www.instagram.com/transcendence.jp/",
    lineup: ["DJ KURI", "DJ MARIA.", "DJ NOBU", "Garçon", "Kohra", "Paquita Gordon", "Takumi Inamoto", "Timnah", "upsammy", "YSK", "Yuzo Iwata", "Zitto B2B Zurkin"],
  },
  {
    id: "99flags",
    type: "festival",
    name: "99flags",
    date: "2026-05-09/2026-05-10",
    location: "Ooba Camp Village",
    city: "Tokyo",
    address: "3741 Okuno, Hinode-machi, Nishitama-gun, Tokyo",
    lat: 35.7421,
    lng: 139.2574,
    image: "images/festivals/99flags.jpeg",
    flyer: "images/festivals/99flags-flyer.jpg",
    genre: ["HOUSE", "MINIMAL"],
    desc: "99flags operates as a nomadic party series across Tokyo's club circuit, drawing from deep techno and house traditions while maintaining an underground ethos. The collective has built a reputation for intimate gatherings that prioritize sound system culture and extended sets over commercial appeal.",
    url: "https://www.99flags.org/",
    instagram: "https://www.instagram.com/99flags_party/",
    lineup: ["MOODMAN", "SHIBATA", "P-YAN", "ATSUKI", "KARUTA", "LEVOLANT", "CONNOR", "RAMI", "DJ BIN", "ABURA", "ENUOH", "MATSUNAMI", "AKG++"],
  },
  {
    id: "the-star-festival",
    name: "THE STAR FESTIVAL",
    date: "2026-05-16/2026-05-17",
    city: "Kyoto",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "THE STAR FESTIVAL brings together Japan's underground electronic music community in Kyoto's historic setting. The festival showcases both established and emerging artists across techno and house, creating an intimate gathering that reflects the city's unique blend of tradition and forward-thinking culture. Known for its carefully curated lineups and atmospheric venues.",
  },
  {
    id: "paramount",
    name: "PARAMOUNT",
    date: "2026-05-23/2026-05-24",
    city: "Gunma",
    genre: ["TECHNO"],
    desc: "PARAMOUNT brings open-air techno to Gunma's natural landscapes, establishing itself as a key destination outside Tokyo's urban circuit. The festival emphasizes raw, uncompromising lineups that reflect Japan's deeper underground currents.",
  },
  {
    id: "letus-music-camp",
    name: "Letus Music Camp",
    date: "2026-05-29/2026-05-31",
    city: "Hyogo",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "Letus Music Camp brings together Japan's underground electronic community in the natural surroundings of Hyogo Prefecture. The festival emphasizes intimate connections between artists and attendees, fostering a collaborative atmosphere that extends beyond typical festival boundaries. Known for its carefully curated lineups that span multiple electronic genres while maintaining focus on the underground scene.",
  },
  {
    id: "matricaria",
    name: "MATRICARIA",
    date: "2026-05-29/2026-05-31",
    city: "Fukushima",
    genre: ["TECHNO", "EXPERIMENTAL"],
    desc: "MATRICARIA brings forward-thinking electronic music to Fukushima's evolving cultural landscape. The festival emphasizes atmospheric programming that bridges experimental soundscapes with dancefloor-focused sets. Its intimate scale allows for deeper artist-audience connections within carefully curated environments.",
  },
  {
    id: "link-open-air",
    name: "Link Open Air",
    date: "2026-05-29T15:00:00.000Z",
    city: "Toyama",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "Link Open Air brings electronic music to Toyama's natural landscapes, creating an intimate gathering that connects sound with environment. The festival showcases both domestic and international artists across thoughtfully curated stages, emphasizing quality over scale in Japan's growing outdoor festival circuit.",
  },
  {
    id: "japonism",
    name: "JAPONISM",
    date: "2026-05-30/2026-05-31",
    city: "Tochigi",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "JAPONISM takes place in the natural surroundings of Nasu, Tochigi, blending electronic music with the region's mountainous landscape. The festival emphasizes the connection between sound and environment, creating an immersive experience away from urban centers. Artists perform across multiple stages that integrate with the outdoor setting.",
  },
  {
    id: "goj-ichi-festival",
    name: "Gojū-Ichi Festival",
    date: "2026-06-05/2026-06-07",
    city: "Tokyo",
    genre: ["TECHNO", "EXPERIMENTAL"],
    desc: "Gojū-Ichi Festival operates as a multi-venue exploration of Tokyo's underground electronic music landscape, typically spanning warehouse spaces and intimate club rooms across the city. The festival emphasizes raw techno and experimental electronic music, drawing from both local Japanese producers and international acts who align with its uncompromising aesthetic.",
  },
  {
    id: "festival-fruezinho-2026",
    name: "FESTIVAL FRUEZINHO 2026",
    date: "2026-06-12T15:00:00.000Z",
    city: "Tokyo",
    genre: ["TECHNO", "HOUSE"],
    desc: "FESTIVAL FRUEZINHO brings São Paulo's underground dance culture to Tokyo for a rare cross-continental exchange. The festival showcases Brazil's distinctive take on techno and house through carefully curated lineups that bridge South American and Japanese electronic music scenes. Expect raw, uncompromising sounds that reflect both cities' commitment to authentic underground culture.",
  },
  {
    id: "dots",
    name: "Dots",
    date: "2026-06-19/2026-06-21",
    city: "Hokkaido",
    genre: ["TECHNO", "EXPERIMENTAL"],
    desc: "Dots operates as Hokkaido's forward-thinking electronic music gathering, positioning itself within Japan's northern underground circuit. The festival curates a focused lineup that bridges techno's harder edges with experimental electronic sounds, drawing both local and touring artists to Sapporo's club infrastructure.",
  },
  {
    id: "samsara",
    name: "SAMSARA",
    date: "2026-06-20/2026-06-21",
    city: "Nagano",
    genre: ["TECHNO", "EXPERIMENTAL"],
    desc: "SAMSARA brings underground electronic music to the mountains of Nagano, creating an intimate connection between nature and sound. The festival focuses on deep, meditative experiences that align with its spiritual namesake, drawing talent from Japan's experimental and techno scenes.",
  },
  {
    id: "halola-camp",
    name: "HALOLA CAMP",
    date: "2026-06-26T15:00:00.000Z",
    city: "Hokkaido",
    genre: ["HOUSE", "TECHNO"],
    desc: "HALOLA CAMP brings together electronic music enthusiasts in Hokkaido's natural landscape for an intimate outdoor gathering. The festival emphasizes community and connection through carefully curated lineups that span house and techno territories. Set against the backdrop of Japan's northernmost island, it offers a more contemplative alternative to urban festival experiences.",
  },
  {
    id: "moment",
    name: "Moment",
    date: "2026-07-03/2026-07-05",
    city: "Nara",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "Moment brings carefully curated electronic programming to Nara's historic landscape, creating an intimate dialogue between ancient surroundings and contemporary sound. The festival maintains a focused approach to artist selection, emphasizing quality over scale while showcasing both established and emerging talent from Japan's underground scene.",
  },
  {
    id: "rural",
    name: "Rural",
    date: "2026-07-17/2026-07-20",
    city: "Fukushima",
    genre: ["TECHNO", "HOUSE", "AMBIENT"],
    desc: "Rural transforms the pastoral landscapes of Fukushima into a contemplative space for electronic music, drawing artists and attendees into dialogue with both sound and environment. The festival emphasizes the relationship between natural settings and underground music culture, creating intimate experiences that reflect the region's resilience and creative spirit.",
  },
  {
    id: "fulirock",
    name: "FuliRock",
    date: "2026-07-24/2026-07-26",
    city: "Niigata",
    genre: ["ELECTRONIC", "MIX"],
    desc: "Fuji Rock Festival transforms the mountains of Naeba into Japan's premier outdoor music gathering each summer. While primarily known for its diverse rock and alternative lineup, the festival has increasingly embraced electronic acts across multiple stages. The natural setting creates an immersive experience that bridges Japan's festival culture with international underground sounds.",
  },
  {
    id: "sonic-mania",
    name: "Sonic Mania",
    date: "2026-08-13T15:00:00.000Z",
    city: "Chiba",
    genre: ["ELECTRONIC", "MIX"],
    desc: "Summer Sonic's electronic-focused sister event brings concentrated doses of dance music to Chiba's festival circuit. The festival curates a focused lineup that spans the electronic spectrum, from harder techno sets to more accessible house programming. A more intimate alternative to the main Summer Sonic experience.",
  },
  {
    id: "one-park-festival",
    name: "ONE PARK FESTIVAL",
    date: "2026-09-05/2026-09-06",
    city: "Fukui",
    genre: ["ELECTRONIC", "HOUSE", "TECHNO"],
    desc: "ONE PARK FESTIVAL brings electronic music to Fukui's natural landscape, creating an intimate gathering that balances underground sounds with outdoor festival atmosphere. The event showcases both domestic and international artists across multiple stages, emphasizing community and connection within Japan's regional festival circuit.",
  },
  {
    id: "re-birth-festival",
    type: "festival",
    name: "Re:birth Festival",
    date: "2026-09-11/2026-09-13",
    location: "Gateaux Kingdom Koumi",
    city: "Nagano",
    address: "5907 Toyosato, Koumi-machi, Minamisaku-gun, Nagano Prefecture",
    lat: 36.054,
    lng: 138.412,
    image: "images/festivals/re-birth-festival.jpg",
    flyer: "images/festivals/re-birth-festival-flyer.jpg",
    genre: ["TECHNO", "HOUSE", "AMBIENT", "LIVE"],
    desc: "Re:birth Festival takes place at the alpine Gateaux Kingdom Koumi venue in Nagano Prefecture, positioning itself within Japan's mountain festival circuit. The event focuses on techno and electronic music programming in a natural setting away from urban centers.",
    url: "https://www.rebirth-fes.com/",
    instagram: "https://www.instagram.com/rebirthfes/",
  },
  {
    id: "ultra-japan",
    name: "Ultra Japan",
    date: "2026-09-19/2026-09-20",
    city: "Tokyo",
    genre: ["ELECTRONIC", "HOUSE"],
    desc: "Ultra Japan brings the global EDM franchise to Tokyo Bay, drawing massive crowds to Odaiba for its signature main stage spectacle. The festival typically features heavyweight international DJs alongside select Japanese acts, maintaining the Ultra brand's focus on peak-time electronic music across multiple stages.",
  },
  {
    id: "otsukimi",
    name: "御月民 -OTSUKIMI-",
    date: "2026-09-28/2026-09-29",
    city: "Nagano",
    genre: ["TECHNO", "ELECTRONIC"],
    desc: "OTSUKIMI takes place in Nagano's mountainous terrain, drawing its name from the traditional Japanese moon-viewing festival. The event brings together Japan's underground techno community in a natural setting that emphasizes the connection between electronic music and seasonal ritual.",
  },
  {
    id: "synapse-festival",
    name: "Synapse Festival",
    date: "2026-10-02/2026-10-04",
    city: "Fukuoka",
    genre: ["TECHNO", "EXPERIMENTAL"],
    desc: "Synapse Festival brings together electronic music's cerebral edge in Fukuoka's intimate venue spaces. The event focuses on deep techno and experimental sounds, drawing artists who prioritize sonic exploration over commercial appeal. Known for its carefully curated lineups that blend local talent with international acts pushing electronic music's boundaries.",
  },
  {
    id: "yagura-2025",
    name: "YAGURA 2025",
    date: "2026-10-10/2026-10-11",
    city: "Gifu",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "YAGURA returns to Gifu's mountainous landscape for another edition of carefully curated electronic music programming. The festival maintains its commitment to showcasing both established and emerging artists within Japan's underground dance scene, set against the region's natural backdrop.",
  },
  {
    id: "labyrinth",
    name: "Labyrinth",
    date: "2026-10-10/2026-10-12",
    city: "Gunma",
    genre: ["TECHNO", "EXPERIMENTAL"],
    desc: "Labyrinth carves out its own space in Gunma's underground landscape, drawing devotees to immersive sonic experiences that blur the boundaries between mind and movement. The festival's commitment to deeper sounds and experimental approaches creates a sanctuary for those seeking substance over spectacle.",
  },
  {
    id: "wonderfruit-kyoto",
    name: "Wonderfruit Kyoto",
    date: "2026-10-21/2026-10-25",
    city: "Kyoto",
    genre: ["HOUSE", "EXPERIMENTAL", "AMBIENT"],
    desc: "Wonderfruit's Kyoto edition transplants the Thai festival's sustainable ethos and genre-spanning programming to Japan's ancient capital. The multi-day event weaves electronic music through curated art installations and environmental consciousness, drawing both local underground heads and international festival circuit veterans. Expect forward-thinking bookings that span leftfield house, experimental electronics, and ambient soundscapes within thoughtfully designed natural settings.",
  },
  {
    id: "festival-de-frue-2026",
    name: "FESTIVAL de FRUE 2026",
    date: "2026-10-30T15:00:00.000Z",
    city: "Shizuoka",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "FESTIVAL de FRUE returns to Shizuoka's natural landscapes, maintaining its commitment to forward-thinking electronic music programming. The festival continues to blend established artists with emerging talent across carefully curated stages that emphasize sound quality and immersive environments.",
  },
  {
    id: "unknown",
    name: "Unknown 2024",
    date: "2024-10-18/2024-10-20",
    city: "Shizuoka",
    genre: ["TECHNO", "EXPERIMENTAL", "AMBIENT"],
    desc: "Unknown operates as a forward-thinking platform for experimental electronic music in Shizuoka, presenting carefully curated lineups that bridge techno's harder edges with ambient and experimental territories. The festival maintains an intimate scale while fostering connections between Japan's underground scenes and international artists pushing electronic music's boundaries.",
  },
  {
    id: "wormhole",
    name: "wormhole2024",
    date: "2024-10-26/2024-10-27",
    city: "Mie",
    genre: ["TECHNO", "EXPERIMENTAL"],
    desc: "wormhole2024 takes place in Mie prefecture, continuing the series' focus on immersive techno experiences in unconventional spaces. The festival maintains its reputation for forward-thinking programming and intimate scale within Japan's regional festival circuit.",
  },
  {
    id: "dom",
    name: "DOM24",
    date: "2024-10-26T15:00:00.000Z",
    city: "Tokyo",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "DOM24 represents Tokyo's commitment to showcasing cutting-edge electronic music within the city's evolving underground landscape. The festival brings together local and international artists across multiple stages, emphasizing both established names and emerging talent from Japan's thriving scene.",
  },
  {
    id: "parallel-world",
    name: "PARALLEL WORLD",
    date: "2024-11-03/2024-11-04",
    genre: ["EXPERIMENTAL", "ELECTRONIC"],
    desc: "PARALLEL WORLD operates as a forward-thinking platform showcasing experimental electronic music and immersive audiovisual experiences. The event series emphasizes boundary-pushing artists and innovative sound design within carefully curated intimate settings.",
  },
  {
    id: "bonna-pot",
    name: "Bonna Pot",
    date: "2024-11-08/2024-11-10",
    city: "Shizuoka",
    genre: ["TECHNO", "HOUSE", "EXPERIMENTAL"],
    desc: "Bonna Pot operates as a grassroots gathering in Shizuoka, focusing on intimate underground sounds away from major urban centers. The festival maintains a community-driven approach, showcasing both local and visiting artists in settings that prioritize musical discovery over commercial appeal.",
  },
  {
    id: "lab",
    name: "LAB.vol.6",
    date: "2025-03-15/2025-03-16",
    city: "Yamanashi",
    genre: ["EXPERIMENTAL", "TECHNO", "ELECTRONIC"],
    desc: "LAB.vol.6 continues Kyokankaku Labo's exploration of underground electronic music in Yamanashi's natural setting. The sixth iteration maintains the collective's focus on experimental sounds and immersive experiences away from urban club environments. Known for curating forward-thinking lineups that blend established and emerging artists in the Japanese underground scene.",
  },
  {
    id: "axiom",
    name: "axiom",
    date: "2025-04-19/2025-04-20",
    city: "Yamanashi",
    genre: ["TECHNO", "EXPERIMENTAL"],
    desc: "axiom brings together Japan's underground electronic music community in the natural setting of Yamanashi prefecture. The festival focuses on deep techno and experimental electronic sounds, creating an intimate gathering away from Tokyo's urban landscape. Known for its carefully curated lineup and immersive outdoor environment.",
  },
  {
    id: "balance",
    name: "Balance",
    date: "2025-05-16/2025-05-18",
    city: "Gunma",
    genre: ["TECHNO", "MINIMAL"],
    desc: "Balance operates as an intimate gathering in Gunma's mountainous terrain, prioritizing careful curation over scale. The festival maintains focus on deeper techno sounds while integrating the natural environment into its programming approach.",
  },
  {
    id: "intergalactic",
    name: "Intergalactic Festival",
    date: "2025-05-30T15:00:00.000Z",
    city: "Chiba",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "Intergalactic Festival brings together international and domestic artists across multiple stages in Chiba, focusing on forward-thinking electronic music programming. The festival has established itself as a key destination for techno and house music enthusiasts seeking quality lineups outside Tokyo's immediate orbit.",
  },
  {
    id: "body-soul",
    name: "Body&SOUL Live in Japan",
    date: "2025-06-07T15:00:00.000Z",
    city: "Tokyo",
    genre: ["HOUSE"],
    desc: "Body&SOUL brings its legendary deep house and soulful dance music ethos from New York to Tokyo. The event maintains the original's commitment to quality sound, intimate atmosphere, and the spiritual connection between music and movement that has defined the brand since the early 90s.",
  },
  {
    id: "signal",
    name: "Signal",
    date: "2025-06-14/2025-06-15",
    city: "Yamanashi",
    genre: ["TECHNO", "ELECTRONIC"],
    desc: "Signal Open Air takes place in Yamanashi's natural setting, drawing artists and dancers away from Tokyo's club circuit for an immersive outdoor experience. The festival maintains focus on underground techno and electronic music programming while utilizing the prefecture's mountainous landscape as backdrop.",
  },
  {
    id: "euphoria",
    name: "Euphoria",
    date: "2025-07-11/2025-07-12",
    city: "Tokyo",
    genre: ["TECHNO", "HOUSE", "EXPERIMENTAL"],
    desc: "Euphoria presents a focused showcase of Tokyo's underground electronic music community through intimate warehouse settings and carefully curated lineups. The festival maintains a raw, stripped-down approach that prioritizes sound system quality and dancefloor connection over commercial production. Known for hosting both established local talent and emerging artists pushing the boundaries of contemporary club music.",
  },
  {
    id: "orbit",
    name: "ORBIT",
    date: "2025-07-11/2025-07-12",
    city: "Fukui",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "ORBIT brings contemporary electronic music to Fukui's intimate club spaces, fostering connections between local and visiting artists. The festival emphasizes careful curation over scale, creating focused experiences that highlight both established and emerging talents within Japan's underground scene.",
  },
  {
    id: "yamauto",
    name: "YAMAUTO",
    date: "2025-08-09/2025-08-18",
    city: "Shiga",
    genre: ["TECHNO", "ELECTRONIC"],
    desc: "YAMAUTO operates as a multi-day electronic music gathering set against the mountainous terrain of Shiga Prefecture. The festival emphasizes extended sets and immersive soundscapes, drawing both local and international acts to its remote location near Lake Biwa.",
  },
  {
    id: "specialflower-festival",
    name: "SPECIALFLOWER FESTIVAL",
    date: "2025-08-10/2025-08-11",
    city: "Ibaraki",
    genre: ["ELECTRONIC", "TECHNO", "HOUSE"],
    desc: "SPECIALFLOWER FESTIVAL brings together Japan's underground electronic music community in Ibaraki's natural surroundings. The festival emphasizes intimate connections between artists and audience, featuring both established and emerging acts across multiple stages. Known for its carefully curated lineup that spans the electronic spectrum while maintaining a cohesive aesthetic vision.",
  },
  {
    id: "loa-lost-paradise",
    name: "LOA-LOST PARADISE-",
    date: "2025-08-16/2025-08-17",
    city: "Ibaraki",
    genre: ["TECHNO", "MINIMAL"],
    desc: "LOA-LOST PARADISE transforms Ibaraki's natural landscape into an immersive techno sanctuary, drawing devotees deep into the prefecture's forested terrain. The festival maintains its underground ethos while delivering uncompromising lineups that blur the boundaries between raw industrial soundscapes and hypnotic minimal structures.",
  },
  {
    id: "sawagi-festival",
    name: "Sawagi Festival",
    date: "2025-08-22/2025-08-24",
    city: "Yamanashi",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "Sawagi Festival takes place in the mountainous Yamanashi prefecture, offering a retreat from Tokyo's urban club circuit. The festival emphasizes Japan's electronic underground with careful curation across multiple stages set against natural backdrops.",
  },
  {
    id: "one-music-camp",
    name: "ONE MUSIC CAMP",
    date: "2025-08-23/2025-08-24",
    city: "Hyogo",
    genre: ["ELECTRONIC", "AMBIENT", "TECHNO"],
    desc: "ONE MUSIC CAMP brings together Japan's electronic music community in the natural setting of Hyogo Prefecture. The festival balances underground dance music with ambient soundscapes, creating an intimate camping experience that emphasizes connection between artists and attendees.",
  },
  {
    id: "global-ark",
    name: "Global Ark",
    date: "2025-08-29/2025-08-31",
    city: "Gunma",
    genre: ["TECHNO", "HOUSE", "EXPERIMENTAL"],
    desc: "Global Ark positions itself as one of Japan's premier outdoor electronic music gatherings, drawing international and domestic artists to Gunma's mountainous terrain. The festival emphasizes immersive sound design and natural integration, creating a temporary autonomous zone for the country's underground dance community.",
  },
  {
    id: "kyoumei-gathering",
    name: "KYOUMEI GatherinG",
    date: "2025-08-29/2025-08-31",
    city: "Hokkaido",
    genre: ["TECHNO", "EXPERIMENTAL"],
    desc: "KYOUMEI GatherinG operates as Hokkaido's bridge between techno's industrial core and Japan's experimental electronic traditions. The festival curates intimate gatherings that emphasize spatial acoustics and community resonance over commercial spectacle. Its northern location allows for extended nocturnal programming that follows the island's unique seasonal rhythms.",
  },
  {
    id: "bondisco",
    name: "BonDisco",
    date: "2025-08-30/2025-08-31",
    city: "Kyoto",
    genre: ["HOUSE"],
    desc: "BonDisco brings disco and house fundamentals to Kyoto's intimate club spaces since 2014. The party maintains a consistent focus on groove-oriented selections that bridge classic disco sensibilities with contemporary dance floor dynamics. Known for creating warm, community-driven atmospheres that emphasize musical heritage over trend-chasing.",
  },
  {
    id: "pure-rave",
    name: "PURE RAVE",
    date: "2025-09-06/2025-09-08",
    city: "Kanto",
    genre: ["TECHNO"],
    desc: "PURE RAVE operates as a raw underground gathering in the Kanto region, stripping away commercial festival aesthetics in favor of uncompromising sound system culture. The event maintains focus on deep, driving techno programming that prioritizes the dance floor experience over production spectacle.",
  },
  {
    id: "big-fun",
    name: "BIG FUN",
    date: "2025-09-06T15:00:00.000Z",
    city: "Hokkaido",
    genre: ["TECHNO", "HOUSE"],
    desc: "BIG FUN brings underground electronic music to Hokkaido's winter landscape, showcasing both international and domestic talent in an intimate setting. The festival has carved out a distinct identity within Japan's northern dance music circuit, emphasizing quality programming over scale.",
  },
  {
    id: "okiraku-camp",
    name: "OKIRAKU CAMP",
    date: "2025-09-13/2025-09-14",
    city: "Wakayama",
    genre: ["ELECTRONIC", "AMBIENT", "MIX"],
    desc: "OKIRAKU CAMP presents a laid-back approach to electronic music programming in Wakayama's natural setting. The festival balances underground dance music with ambient and experimental sounds, creating space for both peak-time energy and contemplative moments. Its relaxed atmosphere attracts artists and attendees seeking an alternative to the intensity of urban club culture.",
  },
  {
    id: "gampeki",
    name: "GAMPEKI",
    date: "2025-09-20/2025-09-21",
    city: "Yamagata",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "GAMPEKI transforms the mountainous landscape of Yamagata into a sanctuary for electronic music, drawing artists and dancers deep into Japan's rural interior. The festival operates as a multi-day gathering that emphasizes the connection between natural environments and underground sound culture.",
  },
  {
    id: "sangenjaya-music-festival",
    name: "SANGENJAYA MUSIC FESTIVAL",
    date: "2025-09-20/2025-09-21",
    city: "Tokyo",
    genre: ["ELECTRONIC", "TECHNO", "HOUSE"],
    desc: "Sangenjaya Music Festival brings together Tokyo's electronic music community in the intimate setting of one of the city's most creative neighborhoods. The festival showcases both established and emerging artists across multiple venues, reflecting the diverse underground scene that defines modern Japanese dance music culture.",
  },
  {
    id: "colors-presents-soundcamp",
    name: "COLORS Presents SOUNDCAMP",
    date: "2025-09-21/2025-09-23",
    city: "Hokkaido",
    genre: ["ELECTRONIC", "TECHNO", "HOUSE"],
    desc: "COLORS Presents SOUNDCAMP brings electronic music to Hokkaido's natural landscape, creating an immersive experience that blends outdoor festival culture with Japan's underground scene. The event showcases a curated selection of domestic and international artists across multiple stages set against the island's distinctive terrain.",
  },
  {
    id: "festival40010",
    name: "Festival40010",
    date: "2025-09-26/2025-09-28",
    city: "Kochi",
    genre: ["TECHNO", "HOUSE"],
    desc: "Festival40010 operates as Kochi's primary underground electronic music gathering, drawing artists and crowds to Shikoku's often-overlooked dance music scene. The festival maintains an intimate scale while showcasing both domestic and international acts across multiple stages.",
  },
  {
    id: "ffkt",
    name: "FFKT",
    date: "2025-09-27/2025-09-28",
    city: "Shizuoka",
    genre: ["TECHNO", "ELECTRONIC"],
    desc: "FFKT takes place in the natural surroundings of Shizuoka, positioning itself as a bridge between Japan's techno underground and international acts. The festival emphasizes immersive sound design and carefully curated lineups that reflect the deeper currents of contemporary electronic music.",
  },
  {
    id: "music-camp-core",
    name: "Music Camp CORE",
    date: "2025-10-03/2025-10-04",
    city: "Toyama",
    genre: ["TECHNO", "ELECTRONIC"],
    desc: "Music Camp CORE brings raw techno programming to Toyama's mountainous landscape, establishing itself as a key destination for Japan's harder electronic sounds. The festival maintains focus on uncompromising lineups that draw from both domestic and international underground circuits.",
  },
  {
    id: "circus",
    name: "CIRCUS",
    date: "2025-10-03T15:00:00.000Z",
    city: "Tokyo",
    genre: ["TECHNO", "HOUSE"],
    desc: "CIRCUS operates as one of Tokyo's most consistent underground techno platforms, programming both established international acts and emerging local talent across intimate warehouse spaces. The collective has built a reputation for uncompromising lineups that prioritize artistic integrity over commercial appeal, maintaining the raw energy that defines the city's after-hours scene.",
  },
  {
    id: "each-story",
    name: "EACH STORY",
    date: "2025-10-04/2025-10-05",
    city: "Nagano",
    genre: ["ELECTRONIC", "TECHNO", "HOUSE"],
    desc: "EACH STORY brings intimate electronic music programming to Nagano's mountain landscape. The festival curates a focused lineup that emphasizes both established and emerging artists across the underground spectrum. Its remote setting creates a unique environment for deeper musical experiences away from urban club contexts.",
  },
  {
    id: "rare-groove",
    name: "Rare Groove",
    date: "2025-10-04/2025-10-05",
    city: "Yamanashi",
    genre: ["HOUSE", "TECHNO", "MINIMAL"],
    desc: "Rare Groove brings together Japan's underground electronic music community in the natural surroundings of Yamanashi Prefecture. The festival focuses on deeper cuts and alternative sounds, drawing selectors who prioritize musical discovery over mainstream appeal. Its intimate scale and curated programming have established it as a destination for those seeking authentic dance music experiences away from urban club circuits.",
  },
  {
    id: "delta-commit",
    name: "DELTA COMMIT",
    date: "2025-10-04/2025-10-05",
    city: "Yamanashi",
    genre: ["TECHNO", "ELECTRONIC"],
    desc: "DELTA COMMIT brings underground electronic music to Yamanashi's natural landscapes, creating an intimate gathering that emphasizes sound quality and community. The festival maintains a carefully curated approach, focusing on both established and emerging artists within Japan's electronic music scene.",
  },
  {
    id: "music-2024",
    name: "＋music 2024",
    date: "2025-10-11/2025-10-12",
    city: "Tokyo",
    genre: ["TECHNO", "HOUSE"],
    desc: "＋music returns to Tokyo with its carefully curated lineup of forward-thinking electronic music. The festival continues to champion both established and emerging artists across the techno and house spectrum, maintaining its reputation as a key gathering point for Japan's underground dance community.",
  },
  {
    id: "ishinoko",
    name: "ishinoko",
    date: "2025-10-11/2025-10-13",
    city: "Ishikawa",
    genre: ["ELECTRONIC", "TECHNO"],
    desc: "ishinoko emerges from Ishikawa's growing electronic music community, offering an intimate platform for both established and emerging artists. The festival emphasizes quality programming over scale, creating space for deeper musical exploration within Japan's regional scene.",
  },
  {
    id: "treks",
    name: "TREKs",
    date: "2025-10-17/2025-10-19",
    city: "Kyoto",
    genre: ["TECHNO", "EXPERIMENTAL"],
    desc: "TREKs operates as Kyoto's forward-thinking electronic music platform, curating intimate gatherings that emphasize artistic depth over commercial appeal. The collective consistently showcases both emerging local talent and established international acts within carefully selected venues that complement the city's cultural landscape.",
  },
  {
    id: "circle",
    name: "Circle",
    date: "2025-10-17/2025-10-19",
    city: "Nagano",
    genre: ["TECHNO", "HOUSE", "MINIMAL"],
    desc: "Circle takes place in Nagano's natural surroundings, offering an intimate gathering focused on underground electronic music. The festival emphasizes community and connection through carefully curated lineups in a more secluded mountain setting.",
  },
  {
    id: "one-park-riverfes",
    name: "ONE PARK RIVERFES",
    date: "2025-10-18/2025-10-19",
    city: "Gifu",
    genre: ["HOUSE", "TECHNO"],
    desc: "ONE PARK RIVERFES brings electronic music to the scenic riverside setting of Gifu Prefecture. The festival combines the natural beauty of its riverbank location with carefully curated lineups spanning house and techno. Its intimate scale allows for a focused experience away from Japan's major metropolitan festival circuit.",
  },
  {
    id: "lost-find",
    name: "Lost&Find",
    date: "2025-10-18/2025-10-19",
    city: "Shizuoka",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "Lost&Find operates in Shizuoka's verdant landscape, positioning itself as a boutique gathering that prioritizes intimate connections between sound and environment. The festival curates a careful balance of underground electronic music within natural settings, drawing a discerning crowd seeking authentic experiences away from urban festival circuits.",
  },
  {
    id: "asagiri-jam",
    name: "ASAGIRI JAM",
    date: "2025-10-18/2025-10-19",
    city: "Shizuoka",
    genre: ["AMBIENT", "ELECTRONIC", "EXPERIMENTAL"],
    desc: "ASAGIRI JAM takes place in the misty highlands of Shizuoka's Fujinomiya region, where the natural amphitheater of Mount Fuji's foothills creates an otherworldly setting for electronic music. The festival blends ambient soundscapes with deeper electronic genres, drawing on the mystical atmosphere of its mountainous location. Known for its intimate scale and focus on sonic experimentation within nature's embrace.",
  },
  {
    id: "dream-festival",
    name: "DREAM FESTIVAL",
    date: "2025-10-18/2025-10-19",
    city: "Yamanashi",
    genre: ["ELECTRONIC", "TECHNO", "HOUSE"],
    desc: "Dream Festival brings electronic music to the natural landscapes of Yamanashi Prefecture, creating an intimate connection between sound and environment. The festival showcases both domestic and international artists across multiple stages, emphasizing the contrast between urban electronic culture and rural Japanese settings.",
  },
  {
    id: "annahme",
    name: "annahme",
    date: "2025-10-25/2025-10-26",
    city: "kochi",
    genre: ["TECHNO", "HOUSE", "MINIMAL"],
    desc: "annahme operates in Kochi, bringing carefully curated electronic music programming to Shikoku's southern coast. The festival maintains an intimate scale while showcasing both domestic and international artists across underground dance music genres.",
  },
  {
    id: "brightness",
    name: "Brightness",
    date: "2025-10-25/2025-10-26",
    city: "Kawasaki",
    genre: ["TECHNO", "HOUSE"],
    desc: "Brightness brings together Japan's underground electronic music community in Kawasaki's industrial landscape. The festival showcases both established and emerging artists across techno and house, maintaining an intimate atmosphere that prioritizes music over spectacle.",
  },
  {
    id: "capsule-2025",
    name: "CAPSULE-山中湖花火音楽祭-2025-",
    date: "2025-10-25/2025-10-26",
    city: "Yamanashi",
    genre: ["ELECTRONIC", "HOUSE"],
    desc: "CAPSULE's annual lakeside gathering returns to Mount Fuji's foothills, combining electronic music with traditional Japanese fireworks displays over Yamanakako's pristine waters. The festival maintains its intimate scale while showcasing both domestic and international acts against one of Japan's most iconic natural backdrops.",
  },
  {
    id: "midnight-cult-rave",
    name: "MIDNIGHT CULT RAVE",
    date: "2025-11-01/2025-11-02",
    city: "Yamanashi",
    genre: ["TECHNO", "EXPERIMENTAL"],
    desc: "MIDNIGHT CULT RAVE operates in the shadows of Yamanashi's mountainous terrain, delivering uncompromising techno programming for Japan's underground faithful. The event maintains strict devotion to darker electronic sounds, creating an intimate sanctuary for the scene's most dedicated followers.",
  },
  {
    id: "mirrorball-village2024",
    name: "Mirrorball Village2024",
    date: "2025-11-01/2025-11-03",
    city: "Nagasaki",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "Mirrorball Village returns to Nagasaki with its signature blend of intimate outdoor settings and carefully curated electronic programming. The festival maintains its focus on creating immersive experiences that merge natural landscapes with forward-thinking dance music across multiple stages.",
  },
  {
    id: "grow-the-culture-open-air",
    name: "GROW THE CULTURE OPEN AIR",
    date: "2025-11-08/2025-11-09",
    city: "Tokyo",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "GROW THE CULTURE OPEN AIR brings Tokyo's underground dance music community together in an outdoor setting that prioritizes authentic electronic music culture. The festival showcases both local and international artists across multiple stages, maintaining focus on quality programming over commercial appeal.",
  },
  {
    id: "iyasaka-rave-festival",
    name: "IYASAKA RAVE FESTIVAL",
    date: "2025-11-14/2025-11-16",
    city: "Okinawa",
    genre: ["TECHNO", "HOUSE", "ELECTRONIC"],
    desc: "IYASAKA RAVE FESTIVAL brings underground electronic music to Okinawa's tropical landscape, creating a unique fusion of island atmosphere and dance floor intensity. The festival showcases both local and international artists across multiple stages, emphasizing the raw energy of rave culture in Japan's southernmost prefecture.",
  },
  {
    id: "topia",
    name: "Topia",
    date: "2025-11-14T15:00:00.000Z",
    city: "Chiba",
    genre: ["TECHNO", "HOUSE"],
    desc: "Topia brings underground electronic music to Chiba's industrial landscape, showcasing both local and international acts across multiple stages. The festival maintains a focus on deeper techno and house sounds, drawing crowds from Tokyo's club scene to experience music in a more expansive outdoor setting.",
  },
  {
    id: "mutek",
    name: "Mutek",
    date: "2025-11-20/2025-11-23",
    city: "Tokyo",
    genre: ["EXPERIMENTAL", "ELECTRONIC", "LIVE"],
    desc: "MUTEK Tokyo brings the Montreal-based festival's signature blend of audiovisual performance and electronic experimentation to Japan's capital. The event showcases cutting-edge digital art installations alongside live electronic music performances, maintaining the brand's focus on innovation at the intersection of sound and visual technology.",
  },
  {
    id: "odyssey",
    name: "Odyssey",
    date: "2025-11-22/2025-11-24",
    city: "Miyazaki",
    genre: ["TECHNO", "ELECTRONIC"],
    desc: "Odyssey brings underground electronic music to Miyazaki's coastal landscape, creating an intimate gathering that bridges Japan's techno scene with the region's natural setting. The festival cultivates a focused sonic experience away from major urban centers, drawing artists and attendees seeking deeper musical connections.",
  },
  {
    id: "takarajima-beach-cleaning-party",
    name: "TAKARAJIMA-Beach Cleaning Party-",
    date: "2025-11-29/2025-11-30",
    city: "Okinawa",
    genre: ["ELECTRONIC", "HOUSE", "TECHNO"],
    desc: "TAKARAJIMA combines environmental activism with electronic music programming on Okinawa's coastline. The festival integrates beach cleaning activities with DJ sets, creating a unique format that addresses ocean conservation while showcasing underground dance music. Participants engage in both ecological restoration and musical celebration across multiple days of programming.",
  },
];

const VENUES = [
  {
    id: "womb",
    name: "WOMB",
    city: "TOKYO",
    area: "SHIBUYA",
    type: "club",
    image: "images/venues/womb.jpg",
    capacity: 800,
    address: "2-16 Maruyama-cho, Shibuya-ku, Tokyo",
    lat: 35.6583,
    lng: 139.695,
    url: "https://www.womb.co.jp/",
    instagram: "https://www.instagram.com/womb_tokyo/",
    desc: "WOMB stands as Tokyo's most iconic techno institution, housed in a striking underground space in Shibuya with a world-class sound system that has drawn international artists for over two decades. The venue's distinctive curved main floor and precise acoustics have cemented its reputation as a pilgrimage site for serious dance music enthusiasts."
  },
  {
    id: "circus-tokyo",
    name: "CIRCUS TOKYO",
    city: "TOKYO",
    area: "SHIBUAYA",
    type: "club",
    image: "images/venues/circus-tokyo.jpeg",
    genre: ["TECHNO", "HOUSE", "MINIMAL", "BASS", "OTHERS"],
    capacity: 300,
    address: "3-26-16 Shibuya, Shibuya-ku, Tokyo",
    lat: 35.6542,
    lng: 139.7056,
    url: "https://circus-tokyo.jp/",
    instagram: "https://www.instagram.com/circus_tokyo/",
    desc: "CIRCUS TOKYO operates as a refined underground space in the heart of Shibuya, known for its carefully curated techno programming and intimate atmosphere. The venue attracts both established international artists and emerging local talent, maintaining a reputation for quality sound systems and discerning crowds. Its compact layout creates an immersive environment where the focus remains firmly on the music."
  },
  {
    id: "saloon",
    name: "SALOON",
    city: "TOKYO",
    area: "SHIBUYA",
    type: "club",
    image: "images/venues/saloon.jpeg",
    genre: ["TECHNO", "HOUSE", "OTHERS"],
    capacity: 150,
    address: "Za-House Building B3F, 1-34-17 Ebisu-Nishi, Shibuya-ku, Tokyo",
    lat: 35.6471,
    lng: 139.7023,
    url: "https://saloon-tokyo.com/",
    instagram: "https://www.instagram.com/saloon_tokyo/",
    desc: "SALOON operates as a compact basement club in Shibuya, known for its intimate atmosphere and carefully curated lineups spanning techno, house, and experimental electronic music. The venue's low ceilings and minimal lighting create an immersive environment that prioritizes sound quality and dancefloor intimacy over spectacle. Its programming often features both emerging local talent and respected international artists within Tokyo's underground circuit."
  },
  {
    id: "solfa",
    name: "SOLFA",
    city: "TOKYO",
    area: "NAKAMEGURO",
    type: "club",
    image: "images/venues/solfa.jpeg",
    genre: ["TECHNO", "HOUSE", "LIVE", "OTHERS"],
    capacity: 200,
    address: "Oak Build, 1-20-5 Aobadai, Meguro-ku, Tokyo.",
    lat: 35.647,
    lng: 139.6981,
    url: "https://nakameguro-solfa.com/",
    instagram: "https://www.instagram.com/solfa_nakameguro/",
    desc: "SOLFA occupies a basement space in Nakameguro, offering an intimate setting for electronic music with a sound system that prioritizes clarity over volume. The venue has cultivated a reputation for quality bookings across house and techno, attracting both local selectors and international artists to its compact dancefloor. Its understated approach and commitment to proper sound design has made it a respected destination within Tokyo's discerning underground community."
  },
  {
    id: "unit",
    name: "UNIT",
    city: "TOKYO",
    area: "DAIKANYAMA",
    type: "livehouse",
    image: "images/venues/unit.jpeg",
    genre: ["TECHNO", "HOUSE", "LIVE", "OTHERS"],
    capacity: 200,
    address: "ZaHOUSE, 1-34-17 Ebisu-Nishi, Shibuya-ku, Tokyo",
    lat: 35.6471,
    lng: 139.7023,
    url: "https://www.unit-tokyo.com/",
    instagram: "https://www.instagram.com/unit_tokyo/",
    desc: "UNIT stands as one of Tokyo's most respected underground venues, housed in a basement space in Daikanyama that prioritizes sound quality and intimate atmosphere over flashy production. The club's carefully curated programming spans techno, house, and experimental electronics, attracting both established international artists and Japan's finest selectors. Its compact layout and dedicated sound system create an immersive environment where music takes precedence over spectacle."
  },
  {
    id: "liquidroom",
    name: "LIQUIDROOM",
    city: "TOKYO",
    area: "EBISU",
    type: "livehouse",
    image: "images/venues/liquidroom.jpg",
    genre: ["TECHNO", "HOUSE", "LIVE", "OTHERS"],
    capacity: 900,
    address: "3-16-6 Higashi, Shibuya-ku, Tokyo",
    lat: 35.6491,
    lng: 139.7106,
    url: "https://www.liquidroom.net/",
    instagram: "https://www.instagram.com/liquidroom_ebisu/",
    desc: "Situated in Ebisu, LIQUIDROOM stands as one of Tokyo's most respected mid-sized venues, hosting everything from international electronic acts to Japan's underground scene regulars. The club's sound system and intimate yet spacious layout have made it a consistent draw for both artists and dedicated ravers since the early 2000s. Its programming spans techno, house, and experimental electronic music with a curatorial approach that balances accessibility with underground credibility."
  },
  {
    id: "clubasia",
    name: "CLUBASIA",
    city: "TOKYO",
    area: "SHIBUYA",
    type: "club",
    image: "images/venues/clubasia.jpg",
    genre: ["TECHNO", "LIVE", "OTHERS"],
    capacity: 800,
    address: "1-8 Maruyama-cho, Shibuya-ku, Tokyo",
    lat: 35.659,
    lng: 139.6953,
    url: "https://clubasia.jp/",
    instagram: "https://www.instagram.com/clubasia/",
    desc: "A cornerstone of Shibuya's club landscape since the late 90s, CLUBASIA spans multiple floors with its main room hosting everything from techno nights to hip-hop showcases. The venue's adaptable layout and central location have made it a reliable stop for both local crews and touring international acts seeking a mid-sized room with solid sound."
  },
  {
    id: "mitsuki",
    name: "MITSUKI",
    city: "TOKYO",
    area: "SHIBUYA",
    type: "club",
    image: "images/venues/mitsuki.jpg",
    genre: ["TECHNO", "HOUSE"],
    capacity: 200,
    address: "Nagashima Daiichi Building B1, 1-22-12 Dogenzaka, Shibuya-ku, Tokyo",
    lat: 35.6565,
    lng: 139.6957,
    url: "https://mitsuki-tokyo.com/",
    instagram: "https://www.instagram.com/mitsuki_tokyo/",
    desc: "MITSUKI operates as an intimate basement club in Tokyo's nightlife landscape, known for its focused programming of underground electronic music. The venue maintains a stripped-down aesthetic that prioritizes sound quality and dancefloor intimacy over spectacle."
  },
  {
    id: "the-room",
    name: "THE ROOM",
    city: "TOKYO",
    area: "SHIBUYA",
    type: "bar",
    image: "images/venues/the-room.jpeg",
    genre: ["HOUSE", "OTHERS", "LIVE"],
    capacity: 80,
    address: "15-19 Sakuragaoka-cho, Shibuya-ku, Tokyo, Daihachi Toto Building",
    lat: 35.6565,
    lng: 139.7016,
    url: "https://theroom.jp/",
    instagram: "https://www.instagram.com/theroom_shibuya/",
    desc: "This intimate Shibuya basement bar operates as a low-key refuge for serious music heads, programming everything from deep house to experimental electronics. The space maintains a deliberately understated atmosphere, drawing a knowing crowd that values sound quality over spectacle. Its compact layout creates an almost living room-like intimacy between DJs and dancers."
  },
  {
    id: "oath",
    name: "OATH",
    city: "TOKYO",
    area: "SHIBUYA",
    type: "bar",
    image: "images/venues/oath.jpeg",
    genre: ["HOUSE", "MINIMAL", "TECHNO"],
    capacity: 100,
    address: "1-6-5 Dogenzaka, Shibuya-ku, Tokyo, B1F",
    lat: 35.6577,
    lng: 139.6992,
    url: "https://www.djbar-oath.com/",
    instagram: "https://www.instagram.com/shibuya_oath/",
    desc: "OATH operates as a DJ bar in Shibuya, maintaining an intimate setting where selectors can explore deeper cuts without the pressure of peak-time crowd dynamics. The venue's compact layout fosters close interaction between artists and audience, creating space for more experimental programming alongside established underground sounds."
  },
  {
    id: "www",
    name: "WWW",
    city: "TOKYO",
    area: "SHIBUAY",
    type: "livehouse",
    image: "images/venues/www.jpeg",
    genre: ["TECHNO", "HOUSE", "LIVE", "OTHERS"],
    capacity: 450,
    address: "Cinema Rise Building B1F, 13-17 Udagawa-cho, Shibuya-ku, Tokyo",
    lat: 35.6615,
    lng: 139.6988,
    url: "https://www-shibuya.jp/",
    instagram: "https://www.instagram.com/www_shibuya/",
    desc: "WWW operates as Shibuya's intimate livehouse where electronic acts perform in a room that prioritizes sound quality over spectacle. The venue's compact layout creates an immersive environment where the boundary between performer and audience dissolves, making it a preferred spot for both established artists and emerging talent to test new material."
  },
  {
    id: "o-east",
    name: "SPOTIFY O-EAST",
    city: "TOKYO",
    area: "SHIBUAYA",
    type: "livehouse",
    image: "images/venues/o-east.jpeg",
    genre: ["TECHNO", "HOUSE", "MINIMAL", "LIVE", "OTHERS"],
    capacity: 1300,
    address: "2-14-8 Dogenzaka, Shibuya-ku, Tokyo",
    lat: 35.6587,
    lng: 139.6956,
    url: "https://shibuya-o.com/east/",
    instagram: "https://www.instagram.com/midnight_east/",
    desc: "One of Shibuya's most established mid-sized venues, O-East has hosted everything from indie rock to underground electronic acts since the late 90s. The space maintains a no-frills approach with solid sound and sightlines that work equally well for live bands and DJ sets. Part of the broader O-family of venues, it sits at the sweet spot between intimate club and proper concert hall."
  },
  {
    id: "bonobo",
    name: "BONOBO",
    city: "TOKYO",
    area: "JINGUMAE",
    type: "bar",
    image: "images/venues/bonobo.jpg",
    genre: ["TECHNO", "HOUSE", "MINIMAL", "AMBIENT", "OTHERS"],
    capacity: 100,
    address: "2-23-4 Jingumae, Shibuya-ku, Tokyo",
    lat: 35.6746,
    lng: 139.7111,
    instagram: "https://www.instagram.com/jingumaebonobo/",
    desc: "A cozy neighborhood bar in Jingu-mae that doubles as an intimate venue for electronic music. The space attracts a discerning crowd drawn to its carefully curated sound and unpretentious atmosphere. Its compact size creates an unusually close connection between artists and audience."
  },
  {
    id: "forestlimit",
    name: "FORESTLIMIT",
    city: "TOKYO",
    area: "HATAGAYA",
    type: "club",
    image: "images/venues/forestlimit.jpg",
    genre: ["TECHNO", "AMBIENT"],
    capacity: 80,
    address: "KODA Building B1F 102, 2-8-15 Hatagaya, Shibuya-ku, Tokyo",
    lat: 35.678,
    lng: 139.6771,
    url: "https://www.forestlimit.com/",
    instagram: "https://www.instagram.com/forestlimit_info/",
    desc: "FORESTLIMIT operates as an intimate basement club in Shibuya, carving out space for experimental electronic music and avant-garde sound art. The venue's stripped-down aesthetic and carefully curated programming attracts artists and audiences seeking alternatives to Tokyo's mainstream club circuit. Its compact layout creates an immersive environment where the boundary between performer and audience dissolves."
  },
  {
    id: "vent",
    name: "VENT",
    city: "TOKYO",
    area: "OMOTESANDO",
    type: "club",
    image: "images/venues/vent.jpeg",
    genre: ["TECHNO", "HOUSE"],
    capacity: 400,
    address: "3-18-19 Minami-Aoyama, Minato-ku, Tokyo",
    lat: 35.6652,
    lng: 139.7129,
    url: "http://vent-tokyo.net/",
    instagram: "https://www.instagram.com/vent.tokyo/",
    desc: "A intimate basement club in Shibuya that has carved out a reputation for uncompromising techno programming since opening in 2016. The venue's stark concrete interior and precise sound system create an environment where the music takes absolute priority over everything else."
  },
  {
    id: "circus-osaka",
    name: "CIRCUS OSAKA",
    city: "OSAKA",
    area: "SHINSAIBASHI",
    type: "club",
    image: "images/venues/circus-osaka.jpg",
    genre: ["TECHNO", "HOUSE", "BASS", "OTHERS"],
    capacity: 200,
    address: "2F, Nakanishi Building, 1-8-16 Nishishinsaibashi, Chuo-ku, Osaka City, Osaka Prefecture",
    lat: 34.675,
    lng: 135.4989,
    url: "https://circus-osaka.com/",
    instagram: "https://www.instagram.com/circus_osaka/",
    desc: "CIRCUS OSAKA operates as one of Osaka's key underground techno destinations, housed in a compact basement space that prioritizes sound system quality over size. The venue consistently programs cutting-edge international and domestic techno acts, maintaining its reputation as a serious club for dedicated heads in the Kansai region."
  },
  {
    id: "club-joule",
    name: "CLUB JOULE",
    city: "OSAKA",
    area: "SHINSAIBASHI",
    type: "club",
    image: "images/venues/club-joule.jpeg",
    genre: ["TECHNO", "HOUSE", "LIVE", "OTHERS"],
    capacity: 500,
    address: "1st, 2nd, 3rd, 4th, and 5th floors, 2-11-7 Nishishinsaibashi, Chuo-ku, Osaka City, Osaka Prefecture",
    lat: 34.6713,
    lng: 135.4979,
    url: "https://club-joule.com/ja/",
    instagram: "https://www.instagram.com/clubjoule_official/",
    desc: "Club Joule operates as one of Osaka's key underground techno spaces, housed in a basement setting that prioritizes sound system quality over aesthetic flourishes. The venue maintains a stripped-back approach that lets the music define the experience, regularly hosting both international techno acts and Japan's leading electronic artists. Its intimate layout creates an intense dance floor dynamic that has made it a fixture in Kansai's techno circuit."
  },
  {
    id: "compufunk",
    name: "COMPUFUNK RECORDS",
    city: "OSAKA",
    area: "KITAHAMA",
    type: "club",
    image: "images/venues/compufunk.jpeg",
    genre: ["TECHNO", "HOUSE", "MINIMAL", "BASS", "AMBIENT"],
    capacity: 100,
    address: "2F, GROW Kitahama Building (Kitahama Building No. 2), 1-29 Kitahama Higashi, Chuo-ku, Osaka City, Osaka Prefecture",
    lat: 34.6904,
    lng: 135.5122,
    url: "https://www.instagram.com/djcompufunk/",
    instagram: "https://www.compufunk.com/?mode=f3",
    desc: "COMPUFUNK RECORDS operates as both record shop and intimate club space in Osaka's underground circuit. The venue maintains a focused approach to analog-driven electronic music, with DJ Compufunk's deep knowledge of obscure funk, electro and early techno informing both the shop's selection and club programming. Its compact dimensions create an immersive listening environment that prioritizes sound quality over scale."
  },
  {
    id: "noon",
    name: "NOON + CAFE",
    city: "OSAKA",
    area: "UMEDA",
    type: "bar",
    image: "images/venues/noon.jpeg",
    genre: ["TECHNO", "HOUSE", "LIVE", "OTHERS"],
    capacity: 100,
    address: "3-3-8 Nakazakinishi, Kita-ku, Osaka City, Osaka Prefecture",
    lat: 34.7071,
    lng: 135.5016,
    url: "https://noon-cafe.com/",
    instagram: "https://www.instagram.com/noon_cafe_nakazaki/",
    desc: "A intimate bar and cafe hybrid in Osaka's Nakazakicho district that bridges daytime coffee culture with late-night music sessions. The compact space hosts DJ sets and small gatherings that feel more like private parties than formal club nights. Known for its carefully curated selection of underground electronic music and relaxed atmosphere that attracts both local diggers and visiting artists."
  },
  {
    id: "triangle",
    name: "TRIANGLE",
    city: "OSAKA",
    area: "SHINSAIBASHI",
    type: "club",
    image: "images/venues/triangle.jpeg",
    genre: ["TECHNO", "HOUSE", "OTHERS"],
    capacity: 250,
    address: "2-18-5 Nishishinsaibashi, Chuo-ku, Osaka City, Osaka Prefecture",
    lat: 34.6722,
    lng: 135.4976,
    url: "https://triangle-osaka.jp/",
    instagram: "https://www.instagram.com/triangleosaka/",
    desc: "Triangle operates as one of Osaka's more intimate underground spaces, housed in a compact basement setting that prioritizes sound quality over scale. The venue has built a reputation for carefully curated lineups that span deeper spectrum techno and experimental electronic music, attracting both local selectors and international acts seeking a more focused environment than the city's larger clubs."
  },
  {
    id: "sunhall",
    name: "SUNHALL",
    city: "OSAKA",
    area: "SHINSAIBASHI",
    type: "livehouse",
    image: "images/venues/sunhall.jpeg",
    genre: ["OTHERS"],
    capacity: 400,
    address: "Big Step South B2, 2-9-28 Nishishinsaibashi, Chuo-ku, Osaka City, Osaka Prefecture",
    lat: 34.6709,
    lng: 135.4984,
    url: "https://sunhall.jp/",
    instagram: "https://www.instagram.com/sunhall.info/",
    desc: "SUNHALL operates as one of Osaka's essential mid-sized venues, bridging the gap between intimate club spaces and larger concert halls. The venue has built its reputation hosting both local underground acts and touring international artists, maintaining a sound system that serves everything from experimental electronics to harder techno lineups. Its consistent programming and accessible Nippombashi location have made it a reliable fixture in Kansai's electronic music circuit."
  },
  {
    id: "club-metro",
    name: "CLUB METRO",
    city: "KYOTO",
    area: "JINGU-MARUTAMACHI",
    type: "club",
    image: "images/venues/club-metro.jpeg",
    genre: ["TECHNO", "HOUSE", "LIVE", "AMBIENT"],
    capacity: 300,
    address: "82 Shimotsutsumi-cho, Sakyo-ku, Kyoto City, Kyoto Prefecture, BF",
    lat: 35.017,
    lng: 135.7727,
    url: "https://www.metro.ne.jp/",
    instagram: "https://www.instagram.com/metro_kyoto/",
    desc: "Metro has anchored Kyoto's underground scene since the early 90s, operating from a converted basement space near Kawaramachi. The club's intimate concrete interior and carefully curated bookings have made it a essential stop for touring artists and a cornerstone of Kansai's electronic music culture."
  },
  {
    id: "snow-machine-japan",
    name: "",
    type: "festival-image",
  },
];