#!/usr/bin/env node
/**
 * build-data-js.mjs — LP/data/*.json → LP/data.js（サイトが読む形）
 *
 * 方針（docs/DATA_SCHEMA.md / Phase 2）:
 *  - スプレッドシート「LP」→ fetch-data.mjs → data/*.json → 本スクリプトで data.js を生成。
 *    data.js は「自動生成物」。手で編集しない（CMSの手動Exportを廃止）。
 *  - 画像パスは配信フォーマットの .webp に正規化（実在するもののみ。無ければ元のまま＋警告）。
 *  - ARTICLES は当面、現行 data.js から引き継ぐ（シート化は後続タスク）。
 *
 * 使い方:
 *   node scripts/build-data-js.mjs             # LP/data.js を生成（上書き）
 *   node scripts/build-data-js.mjs --candidate # LP/data.generated.js に出力（検証用）
 */
import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const LP = path.join(ROOT, 'LP');
const DATA = path.join(LP, 'data');
const ARGS = new Set(process.argv.slice(2));
const OUT = ARGS.has('--candidate') ? path.join(LP, 'data.generated.js') : path.join(LP, 'data.js');

const warnings = [];
const num = v => (v === '' || v == null ? undefined : Number(v));

// 画像を .webp に正規化（存在するもののみ差し替え）
function toWebp(img) {
  if (!img) return img;
  const webp = img.replace(/\.(jpe?g|png)$/i, '.webp');
  if (webp === img) return img;
  if (existsSync(path.join(LP, webp))) return webp;
  warnings.push(`.webp 無し → 元のまま: ${img}`);
  return img;
}

const linksOf = r => {
  const o = {};
  for (const k of ['INSTAGRAM', 'SOUNDCLOUD', 'BANDCAMP']) if (r[k]) o[k.toLowerCase()] = r[k];
  return o;
};

const mapArtist = r => ({ id: r.ID, name: r.NAME, city: r.CITY, country: r.COUNTRY, genre: r.GENRE, image: toWebp(r.IMAGE), bio: r.BIO, links: linksOf(r) });
const mapVenue = r => ({ id: r.ID, name: r.NAME, city: r.CITY, area: r.AREA, type: r.TYPE, image: toWebp(r.IMAGE), capacity: num(r.CAPACITY), address: r.ADDRESS, lat: num(r.LAT), lng: num(r.LNG), url: r.URL, instagram: r.INSTAGRAM, desc: r.DESC });
const mapFest = r => ({ id: r.ID, type: r.TYPE, name: r.NAME, date: r.DATE, location: r.LOCATION, city: r.CITY, address: r.ADDRESS, lat: num(r.LAT), lng: num(r.LNG), image: toWebp(r.IMAGE), imagePosition: r.imagePosition, flyer: toWebp(r.FLYER), genre: (r.GENRE || '').split(/[,·]/).map(s => s.trim()).filter(Boolean), desc: r.DESC, url: r.URL, instagram: r.INSTAGRAM });
const mapEvent = r => ({ name: r.NAME, date: r.DATE, venue: r.VENUE, city: r.CITY, time: r.TIME, desc: r.DESC, lineup: r.LINEUP });

const clean = o => { const x = {}; for (const [k, v] of Object.entries(o)) if (v !== undefined) x[k] = v; return x; };
const loadItems = async name => JSON.parse(await readFile(path.join(DATA, name + '.json'), 'utf8')).items;
const serialize = (name, arr) => `const ${name} = ${JSON.stringify(arr, null, 2)};\n`;

async function main() {
  const artists = (await loadItems('artists')).map(mapArtist).map(clean);
  const venues = (await loadItems('venues')).map(mapVenue).map(clean);
  const festivals = (await loadItems('festivals')).map(mapFest).map(clean);
  const events = (await loadItems('events')).map(mapEvent).map(clean);

  // ARTICLES は現行 data.js から引き継ぐ（後続でシート化）
  const cur = await readFile(path.join(LP, 'data.js'), 'utf8');
  const g = {};
  new Function('g', cur.replace(/const (ARTICLES)\b/g, 'g.$1')).call(null, g);
  const articles = Array.isArray(g.ARTICLES) ? g.ARTICLES : [];

  const header = '/* AUTO-GENERATED by scripts/build-data-js.mjs — 手で編集しない。\n' +
    '   元: スプレッドシート「LP」→ data/*.json。更新は node scripts/build-data-js.mjs。 */\n\n';
  const body = [
    serialize('ARTISTS', artists),
    serialize('EVENTS', events),
    serialize('FESTIVALS', festivals),
    serialize('VENUES', venues),
    serialize('ARTICLES', articles),
  ].join('\n');

  await writeFile(OUT, header + body, 'utf8');
  console.log(`→ ${path.relative(ROOT, OUT)} (artists ${artists.length}, venues ${venues.length}, festivals ${festivals.length}, events ${events.length}, articles ${articles.length})`);
  if (warnings.length) { console.log(`\n警告 ${warnings.length}:`); warnings.slice(0, 20).forEach(w => console.log('  ! ' + w)); }
}
main().catch(e => { console.error('FATAL', e); process.exit(1); });
