#!/usr/bin/env python3
"""Build cache-safe card derivatives from Drive-synced originals."""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "LP" / "images" / "festivals"
OUT_DIR = ROOT / "LP" / "images" / "derivatives" / "card" / "festivals"
OUT_JS = ROOT / "LP" / "image-derivatives.js"
MAX_EDGE = 960
QUALITY = 80


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    mapping = {}
    for source in sorted(SOURCE_DIR.iterdir()):
        if source.suffix.lower() != ".webp":
            continue
        raw = source.read_bytes()
        digest = hashlib.sha256(raw).hexdigest()[:8]
        target = OUT_DIR / f"{source.stem}--{digest}.webp"
        with Image.open(source) as image:
            image = ImageOps.exif_transpose(image)
            if image.mode not in ("RGB", "RGBA"):
                image = image.convert("RGB")
            if max(image.size) > MAX_EDGE:
                image.thumbnail((MAX_EDGE, MAX_EDGE), Image.Resampling.LANCZOS)
            image.save(target, "WEBP", quality=QUALITY, method=6)
        mapping[f"images/festivals/{source.name}"] = f"images/derivatives/card/festivals/{target.name}"

    # 派生画像はハッシュ付きで履歴を持つため、原本更新時に旧版が残る。
    # 原本同期領域には触れず、この生成物ディレクトリだけを安全に整理する。
    wanted = {Path(value).name for value in mapping.values()}
    for stale in OUT_DIR.glob("*.webp"):
        if stale.name not in wanted:
            stale.unlink()

    payload = json.dumps(mapping, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    output = "/* Generated by scripts/build-image-derivatives.py. */\n" \
             f"window.TJ_IMAGE_DERIVATIVES={payload};\n"
    changed = not OUT_JS.exists() or OUT_JS.read_text(encoding="utf-8") != output
    if changed:
        OUT_JS.write_text(output, encoding="utf-8")
        bump_asset_version()
    print(f"Card derivatives: {len(mapping)} festivals → {OUT_DIR.relative_to(ROOT)}")


def bump_asset_version() -> None:
    files = sorted((ROOT / "LP").rglob("*.html"))
    pattern = re.compile(r"(image-derivatives\.js)\?v=(\d+)")
    matches = []
    for path in files:
        text = path.read_text(encoding="utf-8")
        found = list(pattern.finditer(text))
        if found:
            matches.append((path, text, found))
    if not matches:
        return
    version = max(int(m.group(2)) for _, _, found in matches for m in found) + 1
    for path, text, _ in matches:
        path.write_text(pattern.sub(rf"\1?v={version}", text), encoding="utf-8")
    print(f"image-derivatives.js の中身が変わったので ?v={version} へ更新（{len(matches)} ファイル）")


if __name__ == "__main__":
    main()
