#!/usr/bin/env python3
"""カード表示用の縮小画像を、Drive同期の原本から作る。

■ なぜ2サイズ作るか

  カードの実測表示幅は 324〜452px（2026-08-07 / headless で計測）。
  960px 1枚だけだと、スマホには必要の3倍近い画素を送ることになる。
  480px と 960px を作り、srcset でブラウザに選ばせる。
  高解像度ディスプレイでは 480px スロットに 960px が選ばれるので、
  見た目は落とさずスマホの転送量だけが減る。

■ 原本には触らない

  LP/images/ は sync-drive-images.yml が2時間おきに Drive から
  上書きするため、そこへ派生を置くと消えるか毎回差分が出る。
  LP/images/derivatives/ 配下だけを生成物として扱う（AUDIT §9-45）。
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
# 2026-08-15 まで festivals だけを対象にしていた。
# そのため詳細ページの hero（アーティスト・会場・記事）に派生が無く、
# 原寸 1920px をモバイルの 471px 枠へそのまま配っていた。
# 実測でフェス詳細 1,448KB のうち 1,348KB が画像だった（AUDIT §9-90）。
SOURCE_DIRS = ("festivals", "artists", "venues", "articles")
OUT_ROOT = ROOT / "LP" / "images" / "derivatives" / "card"
OUT_JS = ROOT / "LP" / "image-derivatives.js"
# (接尾辞, 長辺上限)。srcset の候補になる。
# カードは 324〜452px、hero はモバイル 471px / PC 約860px。
# 480 / 960 の2枚で両方をまかなえる。
SIZES = (("sm", 480), ("lg", 960))
QUALITY = 80


def main() -> None:
    mapping = {}
    counts = {}
    for kind in SOURCE_DIRS:
        source_dir = ROOT / "LP" / "images" / kind
        out_dir = OUT_ROOT / kind
        if not source_dir.is_dir():
            counts[kind] = 0
            continue
        out_dir.mkdir(parents=True, exist_ok=True)
        n = 0
        for source in sorted(source_dir.iterdir()):
            if source.suffix.lower() != ".webp":
                continue
            raw = source.read_bytes()
            digest = hashlib.sha256(raw).hexdigest()[:8]
            entry = {}
            for suffix, max_edge in SIZES:
                target = out_dir / f"{source.stem}--{digest}-{suffix}.webp"
                with Image.open(source) as image:
                    image = ImageOps.exif_transpose(image)
                    if image.mode not in ("RGB", "RGBA"):
                        image = image.convert("RGB")
                    if max(image.size) > max_edge:
                        image.thumbnail((max_edge, max_edge), Image.Resampling.LANCZOS)
                    image.save(target, "WEBP", quality=QUALITY, method=6)
                    entry[suffix] = {
                        "path": f"images/derivatives/card/{kind}/{target.name}",
                        "w": image.size[0],
                    }
            # 既定( src )は lg。srcset を解釈しない環境でも従来どおり表示できる。
            mapping[f"images/{kind}/{source.name}"] = {
                "src": entry["lg"]["path"],
                "srcset": [[entry["sm"]["path"], entry["sm"]["w"]],
                           [entry["lg"]["path"], entry["lg"]["w"]]],
            }
            n += 1
        counts[kind] = n

        # 派生画像はハッシュ付きで履歴を持つため、原本更新時に旧版が残る。
        # 原本同期領域には触れず、この生成物ディレクトリだけを安全に整理する。
        # ⚠️ 種類ごとに掃除する。全体の wanted で他ディレクトリを消さないこと。
        wanted = {
            Path(p).name
            for key, value in mapping.items()
            if key.startswith(f"images/{kind}/")
            for p, _ in value["srcset"]
        }
        for stale in out_dir.glob("*.webp"):
            if stale.name not in wanted:
                stale.unlink()

    payload = json.dumps(mapping, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    output = "/* Generated by scripts/build-image-derivatives.py. */\n" \
             f"window.TJ_IMAGE_DERIVATIVES={payload};\n"
    changed = not OUT_JS.exists() or OUT_JS.read_text(encoding="utf-8") != output
    if changed:
        OUT_JS.write_text(output, encoding="utf-8")
        bump_asset_version()
    breakdown = " / ".join(f"{k} {v}" for k, v in counts.items())
    print(f"Card derivatives: {len(mapping)}枚 × {len(SIZES)}サイズ（{breakdown}）"
          f" → {OUT_ROOT.relative_to(ROOT)}")


def bump_asset_version() -> None:
    files = sorted((ROOT / "LP").rglob("*.html"))
    pattern = re.compile(r"(image-derivatives\.js)\?v=(\d+)")
    matches = []
    for path in files:
        text = path.read_text(encoding="utf-8")
        found = list(pattern.finditer(text))
        if found:
            matches.append((path, text, found))
    if not matches:
        return
    version = max(int(m.group(2)) for _, _, found in matches for m in found) + 1
    for path, text, _ in matches:
        path.write_text(pattern.sub(rf"\1?v={version}", text), encoding="utf-8")
    print(f"image-derivatives.js の中身が変わったので ?v={version} へ更新（{len(matches)} ファイル）")


if __name__ == "__main__":
    main()
